# Default values for Treatment engine.
replicaCount: 3

image:
  repository: registry.gitlab.com/advinow/javaapis/mica-neo4j-java-services
  pullPolicy: Always
  tag: environment-kube_latest
  imagePullSecrets: regcred-brayest

service:
  vault: http://vault.advinow-utility.int:8200
  role: arn:aws:iam::160988838899:role/role-s3RoleServices-ADVINOW-DEV-S3Role-00a6fae
  region: us-west-2
  environment: environment
  type: NodePort
  port: 8080

hpa:
  min: 3
  max: 3
  cpu: 50
  memory: 50
